### ISSUE TITLE
bug prevents full memery

### ISSUE THREAD

**Issue by irandms** [coolbrow/dankbot#1]
The command

!retro VAPORWAVE?, VAPORWAVE?, VAPORWAVE!

yields only:

Cannot generate retro image.

pls

**Comment by russellcullen** [comment]
Unfortunately that is a limitation of the [source website](https://photofunia.com/categories/all_effects/retro-wave). 

I've already filed a lawsuit for the injustices that this bug has caused on the great users of DankBot.
